### ISSUE TITLE
Labels for English AVSpeech?

### ISSUE THREAD

**Issue by roudimit** [JeongHun0716/Visual-Speech-Recognition-for-Low-Resource-Languages#1]
Hi, thanks for the great work! Can you release the labels / transcripts for English AVSpeech, if you have them?

**Comment by JeongHun0716** [comment]
Hi, thank you for your interest in this project. 
If you send an email to my address sedne246@kaist.ac.kr, I will send you the labels/transcripts for English AVSpeech.

**Comment by OdingdongO** [comment]
> Hi, thank you for your interest in this project. If you send an email to my address [sedne246@kaist.ac.kr](mailto:sedne246@kaist.ac.kr), I will send you the labels/transcripts for English AVSpeech.

Could you please share a copy with me as well? I would greatly appreciate it. I've sent you an email.
